### ISSUE TITLE
RUN /bin/bash /docker-entrypoint.sh -smw step is failing

### ISSUE THREAD

**Issue by RibeyeOnTheBone** [BITPlan/docker-semanticmediawiki#11]
I get the following error at Step 12:

Step 11 : COPY ./image/docker-entrypoint.sh /
 ---> 5220e8cfac0b
Removing intermediate container 51b99233ab88
Step 12 : RUN /bin/bash /docker-entrypoint.sh -smw
 ---> Running in 4677d7b56f0d
[0m[91m/docker-entrypoint.sh: line 30: syntax error near unexpected token `$'{\r''
/docker-entrypoint.sh: line 30:`color_msg() {

The environment is Windows 10. So I am not running ./run script, but 

```
 docker build -t bitplan/smw:0.0.2 .
```

I take it that the {\r is not expected is a line feed problem - Windows v Linux?

Any steer appreciated. 

If I can find a solution I will post it back here - maybe it could be added as a step in the instructions for Windows users.

**Comment by WolfgangFahl** [comment]
Thank you for your feedback. 
Indeed this looks like an incompatibility between Windows and the current state of things. 
The run script is intended as a helping wrapper - it is indeed o.k. to run the build command by itself. 

cd ..With the current git state on my Ubuntu test platform I get
Step 10 : COPY ./image/docker-entrypoint.sh /
stat /var/lib/docker/aufs/mnt/e9683e60a9168d1bd9afb64c8eb150c72cc811377554f9ae1e655548124a9f7e/docker-entrypoint.sh: no such file or directory

which seems to be issue
https://github.com/docker/docker/issues/25925

and
sudo service docker restart

fixes it.
then 

Step 11 : RUN /bin/bash /docker-entrypoint.sh -smw
 ---> Running in 150ace7cc042
Preparing Mediawiki 1.23 docker image
- Starting MySQL database server mysqld
  ...done.
  ...
  Successfully built 8907f3edcc70
  build took 1 minutes and 0 seconds.

works as expected. Please retry with the current git version

**Comment by RibeyeOnTheBone** [comment]
I made some progress with the following
- added dos2unit to the line
RUN apt-get update && apt-get install -y apt-transport-https dos2unix

Then added ran dos2unix againts the .sh files
```
# Copy the install script
COPY ./image/docker-entrypoint.sh /
RUN dos2unix /docker-entrypoint.sh
# run it
RUN /bin/bash /docker-entrypoint.sh -smw
# COPY run script to be used as an entrypoint after installation
COPY ./image/run.sh /
RUN dos2unix /run.sh
```


However, the Docker run of the image fails to start silently, which I read is due to the entry point script failing. So I comment out 
`ENTRYPOINT ["/bin/bash","/run.sh"]
`
and I can get the conainter to start using 

`docker run -d -p 80:80 --name pedantic_raman --hostname=smw bitplan/smw:0.0.2
`
then I try the startup steps manually

```
root@afe68e2a5bc0:/# service mysql start
 * Starting MySQL database server mysqld                                                                                                                         [ OK ]
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.
root@afe68e2a5bc0:/# . /etc/apache2/envvars;
root@afe68e2a5bc0:/# apache2 -X
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message

```
but then I cant access the wiki at all using http://smw/mediawiki or anything with local host.

Attaching the output of the run, in case that helps
[run.txt](https://github.com/BITPlan/docker-semanticmediawiki/files/627875/run.txt)

**Comment by WolfgangFahl** [comment]
Unfortunately docker for mac and docker for windows have a lot of quirks and do not support the same networking options as linux. As of version 0.0.3 the hostname of the os is now being used as is working in linux. If you find the time to retry on windows it would be good to learn about your experience. For the time being i am closing this as "won't fix"
