### ISSUE TITLE
Docker semanticmediawiki docker build  failing in windows at mysql starting step  

### ISSUE THREAD

**Issue by praveenbommali** [BITPlan/docker-semanticmediawiki#14]
As  I'm running the  docker-semanticmediawiki  in the  following env  
OS: Windows 10 
Docker : 18.09.01  
While doing the  docker build , it failing at  docker-entrypoint.sh line 128 on wards  
with the below error .  

> mysql: [Warning] Using a password on the command line interface can be insecure.
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
> mv: cannot stat '/var/www/html/mediawiki-1.27.5/LocalSettings.php': No such file or directory

Please let me  know , what was the exact issue,  
when  i removed  related  lines from sh file and  ran,  it was  building the  images started the  container, of course  , which out mysql, no data will be there ,not able to launch the  application

**Comment by abondrn** [comment]
Just wanted to jump in and say that I had the same issue.

Here are the specs of my environment:
OS: macOS Mojave 10.4
Docker: 18.08.3

I'm working on resolving this, if you've figured this out please let me know.

**Comment by WolfgangFahl** [comment]
Thank you for looking into this. A pull request is welcome. I'd suggest to move to MariaDB while at ti and adopt to the changes needed for Mediawiki 1.31 up. I just did a few changes a few minutes ago but this issue persists.

**Comment by WolfgangFahl** [comment]
we have moved on to https://github.com/WolfgangFahl/pymediawikidocker
