### ISSUE TITLE
proposal: docker compose

### ISSUE THREAD

**Issue by KonradHoeffner** [BITPlan/docker-semanticmediawiki#15]
Unfortunately, we weren't able to install Semantic Media Wiki following the instructions of this repository (see https://github.com/BITPlan/docker-semanticmediawiki/issues/13).

We tried to fix it ourselves but it was complicated to debug with the custom install scripts and the different applications all being in a single docker container.

Have you considered refactoring this container to use Docker Compose? I think having a multi-container setup might be easier to maintain in the future, because one can keep the containers that work and just fix the one that is has a problem.

**Comment by WolfgangFahl** [comment]
As outlined in #13 a personal discussion might help. There are docker compose versions available which are not public yet ...

**Comment by WolfgangFahl** [comment]
we have moved on to https://github.com/WolfgangFahl/pymediawikidocker
