### ISSUE TITLE
Give the built image a Tag like "semanticmediawiki"

### ISSUE THREAD

**Issue by akbitplan** [BITPlan/docker-semanticmediawiki#2]
If it is possible, it would be nice to give the image a tag while it builds. Now i have to look into "docker images" to see which image was built last and copy the id to run it.

**Comment by WolfgangFahl** [comment]
in the run script the names can now be set:

```
# set the names
version="0.0.1"
imagehostname="smw"
imagename="smw"
containername="smw"
```
