### ISSUE TITLE
Needed to update Docker version

### ISSUE THREAD

**Issue by rnwolf** [BITPlan/docker-semanticmediawiki#5]
I use Ubuntu 14.04 as my desktop.

I got the following error:

 ---> Running in 67edde448534
Reading package lists...
Building dependency tree...
Reading state information...
Package dialog is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package apache2
E: Unable to locate package curl
E: Package 'dialog' has no installation candidate
E: Unable to locate package git
E: Unable to locate package libapache2-mod-php5
E: Unable to locate package mysql-server
E: Unable to locate package php5
E: Unable to locate package php5-cli
E: Unable to locate package php5-gd
E: Unable to locate package php5-mysql
The command '/bin/sh -c apt-get install -y  apache2     curl    dialog git  libapache2-mod-php5     mysql-server    php5    php5-cli    php5-gd php5-mysql' returned a non-zero code: 100
build took 0 minutes and 10 seconds.

When I checked my version of docker I found it was 1.7.1.

 docker-semanticmediawiki git:(master) docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d

OS/Arch (server): linux/amd64

I then deleted my current docker application.

sudo apt-get purge lxc-docker*

Updated my repo source to the following:

deb https://apt.dockerproject.org/repo ubuntu-trusty main

Added the repo key:

sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

Then installed the latest version of docker with:

sudo apt-get install docker-engine

Now I recreate the docker container with:

./run.sh -rc

Edit the hosts file as the IP address that the docker build/run did not use the correct IP address. 

sudo vim /etc/hosts

127.0.0.1   localhost smw  
#172.17.0.8 smw

Now I can use my browser and open to get to site.... It takes a while to open on my computer
http://smw/mediawiki/

**Comment by WolfgangFahl** [comment]
thanks for the report
