### ISSUE TITLE
Add MW extensions

### ISSUE THREAD

**Issue by magick93** [BITPlan/docker-semanticmediawiki#8]
Hello

Would it be possible to have the following extensions added:
- [Page Schemas](https://www.mediawiki.org/wiki/Extension:Page_Schemas)
- [Semantic Drilldown](https://www.mediawiki.org/wiki/Extension:Semantic_Drilldown)

Thanks

**Comment by WolfgangFahl** [comment]
yes it would be possible but it's not part of this project on purpose.
