### ISSUE TITLE
Semantic Bundle

### ISSUE THREAD

**Issue by magick93** [BITPlan/docker-semanticmediawiki#9]
Hi

As this is the SMW, it would be very complimentary to have the Semantic Bundle included.

I understand that, as many of this bundle does not use composer, it maybe difficult though.

**Comment by WolfgangFahl** [comment]
Thx for the feedback. This is a base solution on purpose. I have been working on a full fledged installation of extensions pre - installation of pages in a private repository for the last few years. If I find the time I'll publish these as an opensource project. Currently docker has so many quirks that I am a bit frustrated.
